<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dapper.Easies.MySql\Dapper.Easies.MySql.csproj" />
    <ProjectReference Include="..\Dapper.Easies.Tests\Dapper.Easies.Tests.csproj" />
  </ItemGroup>

</Project>
